# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class NIC(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, mac=None, ip=None):  # noqa: E501
        """NIC - a model defined in Swagger

        :param mac: The mac of this NIC.  # noqa: E501
        :type mac: str
        :param ip: The ip of this NIC.  # noqa: E501
        :type ip: str
        """
        self.swagger_types = {
            'mac': str,
            'ip': str
        }

        self.attribute_map = {
            'mac': 'mac',
            'ip': 'ip'
        }

        self._mac = mac
        self._ip = ip

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NIC of this NIC.  # noqa: E501
        :rtype: NIC
        """
        return util.deserialize_model(dikt, cls)

    @property
    def mac(self):
        """Gets the mac of this NIC.


        :return: The mac of this NIC.
        :rtype: str
        """
        return self._mac

    @mac.setter
    def mac(self, mac):
        """Sets the mac of this NIC.


        :param mac: The mac of this NIC.
        :type mac: str
        """

        self._mac = mac

    @property
    def ip(self):
        """Gets the ip of this NIC.


        :return: The ip of this NIC.
        :rtype: str
        """
        return self._ip

    @ip.setter
    def ip(self, ip):
        """Sets the ip of this NIC.


        :param ip: The ip of this NIC.
        :type ip: str
        """

        self._ip = ip
