---
swagger: "2.0"
info: 
  version: "0.0.1"
  title: "Cloudmesh OpenAPI"
  description: "Cloudmesh OpenAPI specifications"
  termsOfService: "http://cloudmesh.org/TBD"
  contact: 
    name: "Cloudmesh OpenAPI Specification"
    url: https://cloudmesh-community.github.io/nist/spec/
    email: laszewski@gmail.com
  license: 
    name: "Apache 2.0"
host: "localhost:8080"
schemes: 
  - "http"
consumes: 
  - "application/json"
produces: 
  - "application/json"
securityDefinitions:
  httpbasic:
    type: basic
  apikey:
    type: apiKey
    in: header
    name: API-Key
  apisecret:
    type: apiKey
    in: header
    name: API-Secret
