swagger: '2.0'
info:
  version: 3.0.1
  title: microservice
  description: |-
  
    As part of microservices, a function with parameters that can be
    invoked has been defined.

    * TODO: assign and improve
    
  termsOfService: 'https://github.com/cloudmesh-community/nist/blob/master/LICENSE.txt'
  contact:
    name: Cloudmesh RESTful Service Example
    url: https://cloudmesh-community.github.io/nist
  license:
    name: Apache
host: 'localhost:8080'
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /cloudmesh/microservices:
    get:
      description: Returns all microservices
      operationId: get_microservice
      produces:
        - application/json
      responses:
        '200':
          description: microservice info
          schema:
            $ref: '#/definitions/Microservice'
    put:
      summary: Create a new microservice
      operationId: add_microservice
      parameters:
        - in: body
          name: microservice
          description: The new microservice to create
          schema:
            $ref: '#/definitions/Microservice'
      responses:
        '201':
          description: Created
  '/cloudmesh/microservice/{name}':
    get:
      description: Returns a microservice
      operationId: get_microservice_by_name
      parameters:
        - name: name
          in: path
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: microservice info
          schema:
            $ref: '#/definitions/Microservice'
definitions:
  Microservice:
    type: object
    description: the microservice
    properties:
      name:
        type: string
        description: name of the microservice
      endpoint:
        type: string
        description: the end point of the microservice
      function:
        type: string
        description: the function the  microservice represents