swagger: '2.0'
info:
  version: 0.0.1
  title: batchjob
  description: |-
    Computing jobs that can run without end user interaction, or are
    scheduled based on resource permission, are called batch
    jobs. Batch jobs are used to minimize human interaction and allow
    the submission and scheduling of many jobs in parallel while
    attempting to utilize the resources through a resource scheduler
    more efficiently or simply in sequential order. Batch processing
    is not to be underestimated even in today’s shifting Internet of
    Things environment towards clouds and containers. This is based on
    the fact that for some applications, resources managed by batch
    queues are highly optimized and in many cases, provide significant
    performance advantages. Disadvantages include the limited and
    preinstalled software stacks that, in some cases, do not allow the
    latest applications to run.
  termsOfService: 'https://github.com/cloudmesh-community/nist/blob/master/LICENSE.txt'
  contact:
    name: Cloudmesh RESTful Service Example
    url: https://cloudmesh-community.github.io/nist
  license:
    name: Apache
host: 'localhost:8080'
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /cloudmesh/batchjobs:
    get:
      description: Returns all batchjobs
      operationId: get_batchjob
      produces:
        - application/json
      responses:
        '200':
          description: batchjob info
          schema:
            $ref: '#/definitions/Batchjob'
    put:
      summary: Create a new batchjob
      operationId: add_batchjob
      parameters:
        - in: body
          name: batchjob
          description: The new batchjob to create
          schema:
            $ref: '#/definitions/Batchjob'
      responses:
        '201':
          description: Created
  '/cloudmesh/batchjob/{name}':
    get:
      description: Returns a batchjob
      operationId: get_batchjob_by_name
      parameters:
        - name: name
          in: path
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: batchjob info
          schema:
            $ref: '#/definitions/Batchjob'
definitions:
  Batchjob:
    type: object
    description: the batchjob
    properties:
      name:
        type: string
        description: name of the batchjob
      output:
        type: string
        description: name of the output file(s) TBD array
      script:
        type: string
        description: the script of the job
      cmd:
        type: string
        description: a command can be scpecified alternatively to the script
      queue:
        type: string
        description: the queue name
      id:
        type: string
        description: after submissin the job gets an id
      cluster:
        type: string
        description: the name of the cluster th job is submitted to
      time:
        type: string
        description: the time the job is to be started
      duration:
        type: string
        description: the duration of the job
      script_path:
        type: string
        description: the path to a script
      nodes:
        type: string
        description: the nodes used to execute the job
      dir:
        type: string
        description: the directory in which to execute the job
