swagger: "2.0"
info:
  version: 3.0.2
  x-date: 10-30-2018
  title: Batch Job
  description: |-
  
    Computing jobs that can run without end user interaction, and are
    scheduled through queuing systems, are called batch jobs. Batch
    jobs are used to minimize human interaction and allow the
    submission and scheduling of many jobs in parallel while
    attempting to utilize the resources through a resource scheduler
    more efficiently or simply in sequential order. Batch processing
    Scarce resources managed by batch queues are highly optimized and
    in many cases, provide significant performance advantages over
    other services. Disadvantages include the limited and preinstalled
    software stacks that, in some cases, do not allow the latest
    applications to run.

  termsOfService: https://github.com/cloudmesh-community/nist/blob/master/LICENSE.txt
  contact:
    name: NIST BDRA Interface Subgroup
    url: https://cloudmesh-community.github.io/nist
  license:
    name: Apache
host: localhost:8080
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /cloudmesh/batch/job:
    get:
      description: Returns all batchjobs
      operationId: get_batchjob
      produces:
        - application/json
      responses:
        200:
          description: batchjob info
          schema:
            $ref: '#/definitions/Batchjob'
    put:
      summary: Create a new batchjob
      operationId: batchjob.add
      parameters:
        - in: body
          name: batchjob
          description: The new batchjob to create
          schema:
            $ref: '#/definitions/Batchjob'
      responses:
        201:
          description: Created
  '/cloudmesh/batch/job/{name}':
    get:
      description: Returns a batchjob
      operationId: batchjob.get_by_name
      parameters:
        - name: name
          in: path
          required: true
          type: string
      produces:
        - application/json
      responses:
        200:
          description: batchjob info
          schema:
            $ref: '#/definitions/Batchjob'
definitions:
  Batchjob:
    type: object
    description: the batchjob
    properties:
      name:
        type: string
        description: name of the batchjob
      output:
        type: string
        description: name of the output file(s) TBD array
      script:
        type: string
        description: the script of the job
      cmd:
        type: string
        description: a command can be scpecified alternatively to the script
      queue:
        type: string
        description: the queue name
      id:
        type: string
        description: after submissin the job gets an id
      cluster:
        type: string
        description: the name of the cluster th job is submitted to
      time:
        type: string
        description: the time the job is to be started
      duration:
        type: string
        description: the duration of the job
      script_path:
        type: string
        description: the path to a script
      nodes:
        type: string
        description: the nodes used to execute the job
      dir:
        type: string
        description: the directory in which to execute the job
      timestamp:
        description: timestamps associated with the resource
        $ref: 'timestamp.yaml#/definitions/Timestamp'
