swagger: "2.0"
info:
  version: 3.1.0
  x-date: 01-29-2019
  x-status: defined
  title: Containers
  description: |-
  
    A service to store containers.
    
  termsOfService: https://github.com/cloudmesh-community/nist/blob/master/LICENSE.txt
  contact:
    name: NIST BDRA Interface Subgroup
    url: https://cloudmesh-community.github.io/nist
  license:
    name: Apache
host: localhost:8080
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /cloudmesh/container:
    get:
      summary: Returns all containers
      description: Returns all containers
      operationId: get_containers
      produces:
        - application/json
      responses:
        200:
          description: containers info
          schema:
            $ref: '#/definitions/Containers'
    put:
      summary: Create a new containers
      description: Create a new containers
      operationId: add_containers
      parameters:
        - in: body
          name: containers
          description: The new containers to create
          schema:
            $ref: '#/definitions/Containers'
      responses:
        201:
          description: Created
  '/cloudmesh/container/{name}':
    get:
      description: Returns a containers
      operationId: get_containers_by_name
      parameters:
        - name: name
          description: name of the container
          in: path
          required: true
          type: string
      produces:
        - application/json
      responses:
        200:
          description: containers info
          schema:
            $ref: '#/definitions/Containers'
definitions:
  Containers:
    type: object
    description: A record representing a container
    properties:
      name:
        type: string
        description: name of the container
      version:
        type: string
        description: version of the container
      label:
        type: string
        description: label of the container
      type:
        type: string
        description: type of the container
      definition:
        type: string
        description: definition or manifest of the container
      imgURI:
        type: string
        description: URI of the container
      tags:
        type: array
        description: tags of the container
        items:
          string
      timestamp:
        description: timestamps associated with the resource
        $ref: 'timestamp.yaml#/definitions/Timestamp'
