swagger: "2.0"
info:
  version: "3.1.0"
  x-status: defined
  x-date: 01-29-2019  
  title: Organization
  description: |-
  
    An important concept in many services is the management of a group
    of users in an organization that includes big data services. User
    management within an organization can be achieved through several
    concepts. First, it can be achieved by defining the
    organization. Second, this organization contains a number of
    users.  Third, users within the organization can have a variety of
    roles and be separated in variopus groups.  These roles and groups
    are used for example to distinguish different access rights to
    services.

  termsOfService: 'https://github.com/cloudmesh-community/nist/blob/master/LICENSE.txt'
  contact:
    name: Cloudmesh REST
    url: https://cloudmesh-community.github.io/nist/spec/
  license:
    name: Apache
host: localhost:8080
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /cloudmesh/organization:
    get:
      description: Returns all users of the organization
      operationId: get_organization
      produces:
        - application/json
      responses:
        '200':
          description: organization info
          schema:
            $ref: '#/definitions/Organization'
    put:
      summary: Create a new organization
      description: Create a new organization
      operationId: add_organization
      parameters:
        - in: body
          name: organization
          description: The new organization to create
          schema:
            $ref: '#/definitions/Organization'
      responses:
        '201':
          description: Created
  '/cloudmesh/organization/{name}':
    get:
      summary: Returns the organization 
      description: Returns the organization
      operationId: get_organization_by_name
      parameters:
        - name: name
          description: The name of the organization
          in: path
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: organization info
          schema:
            $ref: '#/definitions/Organization'
  /cloudmesh/organization/{username}:
    get:
      description: Returns the spcific user of that organization. 
      operationId: get_organization
      produces:
        - application/json
      responses:
        '200':
          description: organization info
          schema:
            $ref: '#/definitions/Organization'
definitions:
  Organization:
    type: object
    properties:
      name:
        description: Name of the organization
        type: string
      users:
        description: list of users
        type: array
        items: 
          $ref: 'user.yaml#/definitions/Users'
      timestamp:
        description: timestamps associated with the organization
        $ref: 'timestamp.yaml#/definitions/Timestamp'

