swagger: "2.0"
info:
  version: "3.1.1"
  x-status: defined
  x-date: 02-15-2019
  title: Organization
  description: |-
  
    An important concept in many services is the management of a group of users
    in an organization that includes big data services. User management within
    an organization can be achieved through several concepts. First, it can be
    achieved by defining the organization. Second, this organization contains a
    number of users.  Third, users within the organization can have a variety of
    roles and be separated in variopus groups.  These roles and groups are used
    for example to distinguish different access rights to services.

  termsOfService: 'https://github.com/cloudmesh-community/nist/blob/master/LICENSE.txt'
  contact:
    name: NIST BDRA Interface Subgroup
    url: https://cloudmesh-community.github.io/nist/spec/
  license:
    name: Apache
host: localhost:8080
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /cloudmesh/organization:
    get:
      tags:
        - Organization
      description: Returns all organizations
      operationId: cloudmesh.organization.get
      produces:
        - application/json
      responses:
        '200':
          description: organization info
          schema:
            $ref: '#/definitions/Organization'
    put:
      tags:
        - Organization
      summary: Create a new organization
      description: Create a new organization
      operationId: cloudmesh.organization.put
      parameters:
        - in: body
          name: organization
          description: The new organization to create
          schema:
            $ref: '#/definitions/Organization'
      responses:
        '201':
          description: Created
  '/cloudmesh/organization/{name}':
    get:
      tags:
        - Organization
      summary: Returns the organization
      description: Returns the organization
      operationId: cloudmesh.organization.get_by_name
      parameters:
        - name: name
          description: The name of the organization
          in: path
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: organization info
          schema:
            $ref: '#/definitions/Organization'
  /cloudmesh/organization/users:
    get:
      tags:
        - Organization
      description: Returns all users of the organization
      operationId: cloudmesh.organization.get_user
      produces:
        - application/json
      responses:
        '200':
          description: organization info
          schema:
            $ref: '#/definitions/Organization'
  /cloudmesh/organization/users/{username}:
    get:
      tags:
        - Organization
      description: Returns the spcific user of that organization.
      operationId: cloudmesh.organization.get_user_by_name
      parameters:
        - name: username
          description: The username
          in: path
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: organization info
          schema:
            $ref: '#/definitions/Organization'
/cloudmesh/organization/users/{username}:
    put:
      tags:
        - Organization
      description: Returns the spcific user of that organization.
      operationId: cloudmesh.organization.put_user
      parameters:
        - name: username
          description: The username
          in: path
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: organization info
          schema:
            $ref: '#/definitions/Organization'
definitions:
  Organization:
    type: object
    properties:
      name:
        description: Name of the organization
        type: string
      users:
        description: list of users
        type: array
        items: 
          $ref: '#/definitions/User'
      timestamp:
        description: timestamps associated with the organization
        $ref: '#/definitions/Timestamp'

