swagger: "2.0"
info:
  version: 3.0.2
  x-date: 10-30-2018
  title: Reservation
  description: |-
  
    Some services may consume a considerable amount of resources,
    necessitating the reservation of resources.

    * TODO: assign and improve
    
  termsOfService: 'https://github.com/cloudmesh-community/nist/blob/master/LICENSE.txt'
  contact:
    name: NIST BDRA Interface Subgroup
    url: https://cloudmesh-community.github.io/nist
  license:
    name: Apache
host: localhost:8080
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /cloudmesh/reservations:
    get:
      tags:
      - Reservation
      summary: Returns all reservations
      description: Returns all reservations
      operationId: cloudmesh.reservation.get
      produces:
        - application/json
      responses:
        '200':
          description: reservation info
          schema:
            type: array
            items:
              $ref: '#/definitions/Reservation'
    put:
      tags:
      - Reservation
      summary: Create a new reservation
      description: Create a new reservation
      operationId: cloudmesh.reservation.add
      parameters:
        - in: body
          name: reservation
          description: The new reservation to create
          schema:
            $ref: '#/definitions/Reservation'
      responses:
        '201':
          description: Created
  '/cloudmesh/reservation/{name}':
    get:
      tags:
      - Reservation
      summary: Returns a reservation
      description: Returns a reservation
      operationId: cloudmesh.reservation.get_by_name
      parameters:
        - name: name
          description: Get reservation info by name
          in: path
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: reservation info
          schema:
            $ref: '#/definitions/Reservation'
definitions:
  Reservation:
    type: object
    description: the reservation
    properties:
      name:
        type: string
        description: name of the reservation
      service:
        type: string
        description: the name of the service on which we reserve
      description:
        type: string
        description: the description of the reservation
      start:
        type: string
        format: date
        description: the start time and date
      end:
        type: string
        format: date
        description: the end time and date
      timestamp:
        description: timestamps associated with the resource
        $ref: '#/definitions/Timestamp'
