swagger: "2.0"
info:
  version: 3.1.1
  x-date: 02-15-2019
  x-status: defined
  title: Scheduler
  description: |-
  
    A service to store scheduler, value, type information. All of them
    are stored as Strings.
    
  termsOfService: 'https://github.com/cloudmesh-community/nist/blob/master/LICENSE.txt'
  contact:
    name: NIST BDRA Interface Subgroup
    url: https://cloudmesh-community.github.io/nist
  license:
    name: Apache
host: localhost:8080
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /cloudmesh/schedulers:
    get:
      description: Returns all schedulers
      operationId: scheduler.get
      produces:
        - application/json
      responses:
        '200':
          description: scheduler info
          schema:
            $ref: '#/definitions/Scheduler'
    put:
      description: Create a new scheduler
      operationId: scheduler.add
      parameters:
        - in: body
          name: scheduler
          description: The new scheduler to create
          schema:
            $ref: '#/definitions/Scheduler'
      responses:
        '201':
          description: Created
  '/cloudmesh/scheduler/{name}':
    get:
      description: Returns a scheduler
      operationId: scheduler.get_by_name
      parameters:
        - name: name
          description: name of the scheduler
          in: path
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: scheduler info
          schema:
            $ref: '#/definitions/Scheduler'
definitions:
  Scheduler:
    type: object
    description: the scheduler
    properties:
      name:
        type: string
        description: name of the scheduler
      value:
        type: string
        description: information of the scheduler
      kind:
        type: string
        description: the scheduler kind or type
      timestamp:
        description: timestamps associated with the resource
        $ref: '#/definitions/Timestamp'
