swagger: "2.0"
info:
  version: 3.0.0
  x-date: 02-08-2019
  title: Batch Job
  description: |-
  
    Computing jobs based on a slurm script that can be run on a remote
    slurm cluster without end user interaction are called Slurm jobs.
    Slurm jobs are helpful to minimize the user's interaction with the
    slurm workload manager and allows seamless communication to the remote
    server. The script as well as the accompanied files are automatically
    transfered to the remote slurm cluster and results are automatically
    collected when ready.

  termsOfService: https://github.com/cloudmesh-community/nist/blob/master/LICENSE.txt
  contact:
    name: Cloudmesh RESTful Service Example
    url: https://cloudmesh-community.github.io/nist
  license:
    name: Apache
host: localhost:8080
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /cloudmesh/batch/job:
    get:
      description: Returns all slurmjobs
      operationId: get_slurmjob
      produces:
        - application/json
      responses:
        200:
          description: slurmjob info
          schema:
            $ref: '#/definitions/Slurmjob'
    put:
      summary: Create a new slurmjob
      operationId: add_slurmjob
      parameters:
        - name: slurmjob
          in: body
          description: The new slurmjob to create
          schema:
            $ref: '#/definitions/Slurmjob'
      responses:
        200:
          description: Created
  '/cloudmesh/slurm/job/{name}':
    get:
      description: Returns a slurmjob
      operationId: get_slurmjob_by_name
      parameters:
        - name: name
          in: path
          required: true
          type: string
      produces:
        - application/json
      responses:
        200:
          description: slurmjob info
          schema:
            $ref: '#/definitions/Slurmjob'
definitions:
  Batchjob:
    type: object
    description: the batch job
    properties:
      name:
        type: string
        description: name of the batch job
      suffix:
        type: string
        description: the suffix of the filename for a job
      clustername:
        type: string
        description: slurm cluster on which the job is gonna run
      input_type:
        type: string
        description: type of the input for the script that is going to be run on remote cluster, possible values are params OR params+file
      remote_path:
        type: string
        description: path in the remotes on which the scripts is gonna be copied to and ran from
      remote_script:
        type: string
        description: name of the script containing the suffix in the remote
      slurm_script_path:
        type: string
        description: path of the slurm script
      job_script_path:
        type: string
        description: path of the file that is going to be run on the cluster via slurm script
      argfile_path:
        type: string
        description: path of the file that has to be passed to the file as an argument (if any)
      local_path:
        type: string
        description: local path to which the results are gonna be copied
