swagger: "2.0"
info:
  version: 3.1.1
  x-status: defined
  x-date: 02-15-2019
  title: Timestamp
  description: |-
  
    Data often need to be timestamped to indicate when it has been
    accessed, created, or modified. All objects defined in this
    document will have, in their final version, a timestamp.
    The date-time string is defined in
    [RFC3339](https://xml2rfc.ietf.org/public/rfc/html/rfc3339.html#anchor14).

  termsOfService: 'https://github.com/cloudmesh-community/nist/blob/master/LICENSE.txt'
  contact:
    name: NIST BDRA Interface Subgroup
    url: https://cloudmesh-community.github.io/nist/spec/
  license:
    name: Apache
host: localhost:8080
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /cloudmesh/timestamp:
    get:
      tags:
        - Timestamp
      description: Returns all timestamps
      summary: Returns all timestamps
      operationId: timestamp.get
      produces:
        - application/json
      responses:
        '200':
          description: timestamp info
          schema:
            $ref: '#/definitions/Timestamp'
    put:
      tags:
        - Timestamp
      summary: Create a new timestamp
      description: Create a new timestamp
      operationId: timestamp.put
      parameters:
        - in: body
          name: timestamp
          description: The new timestamp to create
          schema:
            $ref: '#/definitions/Timestamp'
      responses:
        '201':
          description: Created
  '/cloudmesh/timestamp/{name}':
    get:
      tags:
        - Timestamp
      summary: Returns a timestamp
      description: Returns a timestamp
      operationId: timestamp.get_by_name
      parameters:
        - name: name
          in: path
          required: true
          type: string
          description: the name of the time stamp
      produces:
        - application/json
      responses:
        '200':
          description: timestamp info
          schema:
            $ref: '#/definitions/Timestamp'
definitions:
  Timestamp:
    type: object
    description: the timestamp
    properties:
      accessed:
        type: string
        format: date-time
        description: The time stamp when the object was last accessed
      created:
        type: string
        format: date-time
        description: The time stamp when the object was created 
      modified:
        type: string
        format: date-time
        description: The time stamp when the object was modified        
