openapi: "3.0.2"
info:
  version: 3.2.0
  x-date: 08-06-2019
  x-status: TODO
  title: Virtual Machine
  description: |-

    Vm is a service to manage virtual machines.
    
  termsOfService: https://github.com/cloudmesh-community/nist/blob/master/LICENSE.txt
  contact:
    name: NIST BDRA Interface Subgroup Service
    url: https://cloudmesh-community.github.io/nist/spec/
  license:
    name: Apache 2.0
    url: https://github.com/cloudmesh/cloudmesh-nist/blob/master/LICENSE.txt
servers:
  - url: /cloudmesh/v3
paths:
  /vm/{cloud}:
    get:
      tags:
        - Vm
      summary: Returns a list of virtual machines for the cloud
      description: Returns a list of all virtual machines
      operationId: cloudmesh.vm.list
      parameters:
        - name: cloud
          in: path
          required: true
          schema:
            type: string
          description: The name of the cloud
      responses:
        '200':
          description: The list of virtual machines
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Vm'
        '400':
           description: No Vm found
        '401':
          description: Not authorized
    put:
      tags:
        - Vm
      summary: Add a virtual machine
      description: Sets the named virtual machine
      operationId: cloudmesh.vm.add
      parameters:
        - name: cloud
          in: path
          required: true
          schema:
            type: string
          description: The name of the cloud
      requestBody:
        description: The virtual machine to add or modify
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Vm'
      responses:
        '200':
          description: Vm updated
        '400':
          description: Error updating virtual machine
        '401':
          description: Not authorized
  /vm/{cloud}/{name}:
    get:
      tags:
        - Vm
      summary: Returns the named virtual machine
      description: Returns a virtual machine by name
      operationId: cloudmesh.vm.find_by_name
      parameters:
        - name: cloud
          in: path
          description: The name of the cloud
          required: true
          schema:
            type: string
        - name: name
          in: path
          description: The name of the virtual machine
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Returning the information of the virtual machine
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vm'
        '400':
           description: No Vm found
        '401':
          description: Not authorized
        '404':
           description: The named virtual machine could not be found
    delete:
      tags:
        - Vm
      summary: Deletes the named virtual machine
      description: Deletes a virtual machine by name
      operationId: cloudmesh.vm.delete_by_name
      parameters:
        - name: cloud
          description: The name of the cloud
          in: path
          required: true
          schema:
            type: string
        - name: name
          in: path
          description: The name of the virtual machine
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Deletion successful
        '400':
           description: No Vm found
        '401':
          description: Not authorized
        '404':
           description: The named virtual machine could not be found
components:
  schemas:
    Vm:
      type: object
      properties:
        provider:
          type: string
          description: Name of the provider
        name:
          type: string
          description: the unique name of the virtual machine
        image:
          type: string
          description: the image name for the virtual machine
        flavor:
          type: string
          description: the flavor name for the virtual machine
        region:
          type: string
          description: an optional region
        state:
          type: string
          description: The state of the virtual machine
        private_ips:
          type: string
          description: The private IPs
        public_ips:
          type: string
          description: The public IPS
        metadata:
          type: string
          description: The meta data passed along to the virtual machine

