swagger: "2.0"
info:
  version: 3.2.0
  x-date: 05-23-2019
  title: Batch Job
  description: |-
  
    Computing jobs that can run without end user interaction, and are
    scheduled through queuing systems, are called batch jobs. Batch
    jobs are used to minimize human interaction and allow the
    submission and scheduling of many jobs in parallel while
    attempting to utilize the resources through a resource scheduler
    more efficiently or simply in sequential order. Batch processing
    scarce resources managed by batch queues are highly optimized and
    in many cases, provide significant performance advantages over
    other services. Disadvantages include the limited and pre-installed
    software stacks that, in some cases, do not allow the latest
    applications to run.

  termsOfService: 'https://github.com/cloudmesh/cloudmesh-nist/blob/master/LICENSE.txt'
  contact:
    name: NIST BDRA Interface Subgroup
    url: https://cloudmesh-community.github.io/nist
  license:
    name: Apache
host: localhost:8080
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
basePath: "/cloudmesh/v3"
paths:
  /batch/job:
    get:
      tags:
        - Batchjob
      summary: Returns all batchjobs
      description: Returns all batchjobs
      operationId: cloudmesh.batchjob.get
      produces:
        - application/json
      responses:
        200:
          description: batchjob info
          schema:
            type: array
            items:
              $ref: '#/definitions/Batchjob'
    put:
      tags:
        - Batchjob
      summary: Create a new batchjob
      description: Create a new batchjob
      operationId: cloudmesh.batchjob.add
      parameters:
        - in: body
          name: batchjob
          description: The new batchjob to create
          schema:
            $ref: '#/definitions/Batchjob'
      responses:
        201:
          description: Created
  '/batch/job/{name}':
    get:
      tags:
        - Batchjob
      summary: Returns a batchjob
      description: Returns a batchjob
      operationId: cloudmesh.batchjob.get_by_name
      parameters:
        - name: name
          description: Get batchjob info by name
          in: path
          required: true
          type: string
      produces:
        - application/json
      responses:
        200:
          description: batchjob info
          schema:
            $ref: '#/definitions/Batchjob'
